name: Release MoneyBook

on:
  push:
    tags:
      - 'v*'

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Build Android AAB
        run: |
          cd android
          ./gradlew bundleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: moneybook-${{ github.ref_name }}-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: moneybook-${{ github.ref_name }}-release.aab
          path: android/app/build/outputs/bundle/release/app-release.aab

  create-release:
    needs: build-android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: moneybook-${{ github.ref_name }}-release.apk

      - name: Download AAB artifact
        uses: actions/download-artifact@v4
        with:
          name: moneybook-${{ github.ref_name }}-release.aab

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            moneybook-${{ github.ref_name }}-release.apk
            moneybook-${{ github.ref_name }}-release.aab
          body: |
            ## 🎉 MoneyBook ${{ github.ref_name }} Release

            ### 📱 What's New
            - Multi-account support with individual balances
            - Beautiful transaction modals with validation
            - Custom date selection for transactions
            - Advanced transaction filtering
            - Enhanced UI with gradient backgrounds
            - Negative balance alerts

            ### 📦 Installation
            - **APK**: Direct installation on Android devices
            - **AAB**: For Google Play Store distribution

            ### 🛠️ Build Info
            - React Native 0.80.1
            - WatermelonDB for high-performance database
            - TypeScript for type safety
            - Hermes JavaScript engine

            ### 📋 Requirements
            - Android 5.0+ (API level 21+)
            - 100MB+ free storage space

            ### 🔧 Troubleshooting
            If installation fails, ensure:
            - Unknown sources are enabled
            - Sufficient storage space
            - No conflicting app versions
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-package:
    needs: build-android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@mozaddedalfeshani'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
